branches:
  only:
    - master

# NOTE: only static linking, i.e. via .lib file supported
#  -D BUILD_SHARED_LIBS=OFF;
# extern "C" {  would have to be added to subprojects

build_script:
  - git submodule update --init --recursive
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # - set PATH=%PATH:C:/Program_Files/Git/usr/bin/;=%
  # - rm "C:/Program Files/Git/usr/bin/sh.exe"
  - set PATH=C:\MinGW\bin;%PATH%
  - rm "C:/Program Files/Git/usr/bin/sh.exe"
  - cmake -E make_directory build
  # TODO: make this work
  # - cmake -E chdir build cmake -D ACADOS_WITH_QPOASES=ON -D BLASFEO_TARGET=GENERIC -D HPIPM_TARGET=GENERIC -D BUILD_SHARED_LIBS=OFF  -D ACADOS_EXAMPLES=ON ..
  - cmake -E chdir build cmake -D ACADOS_WITH_QPOASES=ON -D BLASFEO_TARGET=GENERIC -D HPIPM_TARGET=GENERIC -D BUILD_SHARED_LIBS=OFF -G "MinGW Makefiles" ..
  - cmake --build build --config Release
  - cmake -E chdir build ctest -V
