
branches:
  only:
    - msvc

install:
  - call C:\Miniconda36-x64\Scripts\activate.bat
  - conda install --yes -c msys2 m2w64-gcc-libgfortran m2w64-openblas

build_script:
  - git submodule update --init --recursive
  - cmake -E make_directory build
  - cmake -E chdir build cmake ..
  - cmake --build build --config Debug
  - cmake --build build --target test
  - cmake --build build --config Release
  - cmake --build build --target test
