branches:
  only:
    - master

# NOTE: only static linking, i.e. via .lib file supported
#  -D BUILD_SHARED_LIBS=OFF;
# extern "C" {  would have to be added to subprojects

build_script:
  - git submodule update --init --recursive
  # MinGW files need to be at the beginning of the PATH
  - set PATH=C:\MinGW\bin;%PATH%
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - rm "C:/Program Files/Git/usr/bin/sh.exe"
  - cmake -E make_directory build
  - cmake -E chdir build cmake -D ACADOS_WITH_QPOASES=ON -D BLASFEO_TARGET=GENERIC -D HPIPM_TARGET=GENERIC -D BUILD_SHARED_LIBS=OFF -D ACADOS_EXAMPLES=ON -D ACADOS_UNIT_TESTS=ON -G "MinGW Makefiles" ..
  - cmake --build build --config Release
  - cmake -E chdir build ctest -V
